ERROR - 2023-02-24 13:41:12 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
 in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'testeci4', 3306, '', 0)
#1 C:\xampp\htdocs\food\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\food\system\Database\Database.php(67): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\food\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\food\system\Database\Seeder.php(97): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\food\system\Commands\Database\Seed.php(69): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\food\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\food\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\food\spark(97): CodeIgniter\CLI\Console->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
 in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\food\system\Database\Database.php(67): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\food\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\food\system\Database\Seeder.php(97): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\food\system\Commands\Database\Seed.php(69): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\food\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\food\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\food\spark(97): CodeIgniter\CLI\Console->run()
#8 {main}
CRITICAL - 2023-02-24 13:41:12 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\Database.php(67): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(97): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(69): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 ROOTPATH\spark(97): CodeIgniter\CLI\Console->run()
CRITICAL - 2023-02-24 16:47:08 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 226.
 1 SYSTEMPATH\CodeIgniter.php(226): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(190): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-02-24 16:47:20 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 226.
 1 SYSTEMPATH\CodeIgniter.php(226): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(190): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-02-24 16:47:33 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 226.
 1 SYSTEMPATH\CodeIgniter.php(226): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(190): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2023-02-24 19:45:02 --> mysqli_sql_exception: Unknown column 'criado_em' in 'field list' in C:\xampp\htdocs\foodDelivery\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\foodDelivery\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\foodDelivery\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\foodDelivery\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\foodDelivery\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\foodDelivery\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\foodDelivery\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\foodDelivery\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\foodDelivery\app\Database\Seeds\UsuarioSeeder.php(20): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\foodDelivery\system\Database\Seeder.php(146): App\Database\Seeds\UsuarioSeeder->run()
#9 C:\xampp\htdocs\foodDelivery\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#10 C:\xampp\htdocs\foodDelivery\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#11 C:\xampp\htdocs\foodDelivery\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#12 C:\xampp\htdocs\foodDelivery\spark(97): CodeIgniter\CLI\Console->run()
#13 {main}
ERROR - 2023-02-24 19:45:46 --> mysqli_sql_exception: Unknown column 'criado_em' in 'field list' in C:\xampp\htdocs\foodDelivery\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\foodDelivery\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\foodDelivery\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\foodDelivery\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\foodDelivery\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\foodDelivery\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\foodDelivery\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\foodDelivery\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\foodDelivery\app\Database\Seeds\UsuarioSeeder.php(20): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\foodDelivery\system\Database\Seeder.php(146): App\Database\Seeds\UsuarioSeeder->run()
#9 C:\xampp\htdocs\foodDelivery\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#10 C:\xampp\htdocs\foodDelivery\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#11 C:\xampp\htdocs\foodDelivery\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#12 C:\xampp\htdocs\foodDelivery\spark(97): CodeIgniter\CLI\Console->run()
#13 {main}
